// Code generated by MockGen. DO NOT EDIT.
// Source: hash_storage.go

// Package mock_data is a generated GoMock package.
package mock_data

import (
	reflect "reflect"

	data "github.com/ScienceSoft-Inc/integrity-sum/internal/data"
	k8s "github.com/ScienceSoft-Inc/integrity-sum/pkg/k8s"
	gomock "github.com/golang/mock/gomock"
)

// MockIHashStorage is a mock of IHashStorage interface.
type MockIHashStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIHashStorageMockRecorder
}

// MockIHashStorageMockRecorder is the mock recorder for MockIHashStorage.
type MockIHashStorageMockRecorder struct {
	mock *MockIHashStorage
}

// NewMockIHashStorage creates a new mock instance.
func NewMockIHashStorage(ctrl *gomock.Controller) *MockIHashStorage {
	mock := &MockIHashStorage{ctrl: ctrl}
	mock.recorder = &MockIHashStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHashStorage) EXPECT() *MockIHashStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIHashStorage) Get(dirPath string, deploymentData *k8s.DeploymentData) ([]*data.HashData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", dirPath, deploymentData)
	ret0, _ := ret[0].([]*data.HashData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIHashStorageMockRecorder) Get(dirPath, deploymentData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIHashStorage)(nil).Get), dirPath, deploymentData)
}

// PrepareQuery mocks base method.
func (m *MockIHashStorage) PrepareQuery(allHashData []*data.HashData, deploymentData *k8s.DeploymentData) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareQuery", allHashData, deploymentData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// PrepareQuery indicates an expected call of PrepareQuery.
func (mr *MockIHashStorageMockRecorder) PrepareQuery(allHashData, deploymentData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareQuery", reflect.TypeOf((*MockIHashStorage)(nil).PrepareQuery), allHashData, deploymentData)
}
