FROM golang:1.19.5-alpine
RUN apk update && apk add \
    binutils \
    build-base \
    cmake \
    make \
    gcc \
    g++ \
    git \
    libgcc \
    musl-dev \
    util-linux-dev \
    linux-headers \
    bash \
    nano \
    wget \
    mc
CMD [ "/bin/bash" ]
