// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.go

// Package mock_k8s is a generated GoMock package.
package mock_k8s

import (
	reflect "reflect"

	k8s "github.com/ScienceSoft-Inc/integrity-sum/pkg/k8s"
	gomock "github.com/golang/mock/gomock"
)

// MockIKuberService is a mock of IKuberService interface.
type MockIKuberService struct {
	ctrl     *gomock.Controller
	recorder *MockIKuberServiceMockRecorder
}

// MockIKuberServiceMockRecorder is the mock recorder for MockIKuberService.
type MockIKuberServiceMockRecorder struct {
	mock *MockIKuberService
}

// NewMockIKuberService creates a new mock instance.
func NewMockIKuberService(ctrl *gomock.Controller) *MockIKuberService {
	mock := &MockIKuberService{ctrl: ctrl}
	mock.recorder = &MockIKuberServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKuberService) EXPECT() *MockIKuberServiceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockIKuberService) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockIKuberServiceMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIKuberService)(nil).Connect))
}

// GetDataFromDeployment mocks base method.
func (m *MockIKuberService) GetDataFromDeployment() (*k8s.DeploymentData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataFromDeployment")
	ret0, _ := ret[0].(*k8s.DeploymentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataFromDeployment indicates an expected call of GetDataFromDeployment.
func (mr *MockIKuberServiceMockRecorder) GetDataFromDeployment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataFromDeployment", reflect.TypeOf((*MockIKuberService)(nil).GetDataFromDeployment))
}

// RestartPod mocks base method.
func (m *MockIKuberService) RestartPod() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartPod")
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartPod indicates an expected call of RestartPod.
func (mr *MockIKuberServiceMockRecorder) RestartPod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartPod", reflect.TypeOf((*MockIKuberService)(nil).RestartPod))
}
